### ISSUE TITLE
Support for Google Voice

### ISSUE THREAD

**Issue by dougw03** [AllenBurgett/hangouts_takeout_to_backupandrestore#17]
Hi, thank you for taking the time to develop this tool. I was wondering if you would consider adding support for those of us trying to migrate from Google Voice to SMS Backup and Restore. I have about 10 years of GVoice SMS/MMS in my google takeout archive and would like to use the same approach to migrate this data so that I can switch off of GVoice. Thank you again for your contributions

**Comment by AllenBurgett** [comment]
Hi @dougw03, this project is no longer continuing support since Hangouts sunset. You are welcome to create a branch off of this project and reuse any of the code that's reusable for tackling a GVoice project. I don't have a GVoice account and would not have the data model required to tackle that project. 

Best,
Allen

**Comment by dougw03** [comment]
Thank you @AllenBurgett. Unfortunately I lack the technical skills to complete this task. Would you have any interest in taking on this project for a nominal cash reward? It is quite simple and free to create a GV account and (ostensibly) create a data model from there. 

Unfortunately Google has effectively stopped updating GV with new features and there are many of us that are stuck on the GV platform because there are no tools to facilitate migrating our data to standard Android XML. You can email me at this user name at gmail if interested in discussing further. Thanks again
