### ISSUE TITLE
test.xml isn't recognized as an importable file

### ISSUE THREAD

**Issue by iandouglas** [AllenBurgett/hangouts_takeout_to_backupandrestore#8]
First off, thanks so much for this tool!

I tried using it today and the script processed about 27,000 conversations from Hangouts. When I download the file to my phone, the SMS Backup & Restore app doesn't allow me to import the file. It can FIND the text.xml file, but I cannot tap on it to start a restore.

Also, I noticed your script doesn't prepend a standard XML header line, like
```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
```
I added it, re-downloaded, but the app will still not allow me to import that file.

I backed up a few SMS messages using the app, and noticed it also included a comment line like
```xml
<!--File Created By SMS Backup & Restore v10.05.612 on 16/12/2019 10:34:44-->
```
so I added that line too, and incremented the timestamp by one second, and renamed the text.xml file to a similarly-named `sms-2019etc.xml` file, also incremented by one second, and the app still refuses to allow me to import the file.

Edit: more context below

The SMS Backup & Restore app can see the new XML files on Google Drive. I also tried locally copying the files to /data/user/0/com.riteshsahu.SMSBackupRestore/files and into /storage/emulated/0/SMSBackupRestore ... the app won't allow me to navigate into the latter folder. I'm going to try the email attachment feature next.

**Comment by AllenBurgett** [comment]
27000 conversations sounds like a lot. How big is the XML file it generated? I imagine that Backup and Restore might have an upper limit on the size of an xml.

**Comment by iandouglas** [comment]
It's about 9MB total. I was able to manually restore each individual conversation, but it took over half an hour :) Still, I'm thankful that your script did most of the heavy lifting.

**Comment by AllenBurgett** [comment]
I'm glad you got it to work! That doesn't seem that large, I think mine was 15MB. I wonder if something is happening with B&R. Had someone reach out to me, because the messages didn't show up after being restored. Followed B&R's FAQ that suggested they were seeing problems with the new Messages update. I wonder if this is impacting other pieces of the restore.

**Comment by iandouglas** [comment]
After restoring them manually, they also did not show up, but I cleared the Messages app storage and restarted and they were all there (along with hundreds of notifications...). I also had to unlink my web-based Messages app in my desktop browser and re-link to have them show up there as well.

**Comment by haxx0r07** [comment]
I had to use the System Browser in the SMS B&R app (Switch to the local tab and then click the hamburger menu in the upper right) and then browse for my file. Once I selected it there everything else worked as expected.

**Comment by iandouglas** [comment]
> I had to use the System Browser in the SMS B&R app (Switch to the local tab and then click the hamburger menu in the upper right) and then browse for my file. Once I selected it there everything else worked as expected.

I used the System Browser as well, it still wouldn't let me select the file. It was ghosted out like the file format was invalid or something.

**Comment by mmindenhall** [comment]
Just another data point, I'm seeing the same behavior as @iandouglas.  The file is visible in the system browser, but greyed out in the UI.  I'm wondering if there's a file size limit on the ad-supported version?

**Comment by AllenBurgett** [comment]
@mmindenhall, out of curiosity, how big is your xml file? The one I've used for testing is 20Mb. I'd like to increase the size of it to see if I can duplicate the error.

**Comment by mmindenhall** [comment]
The file is only about 3.5MB.

**Comment by mmindenhall** [comment]
I got this to work.  Here are the steps I took.

1. Cleared SMS B&R storage, went through setup again.  Added Google Drive, and gave access to all files and folders (instead of just those created by the app)
1. Ran a backup with SMS B&R (this was just a few messages), so I could compare the files.
1. Ran this tool against my `Hangouts.json`, producing the `test.xml` file.  Renamed this file to follow the filename pattern used by SMS B&R:  `sms-yyyymmddhhmmss.xml`.
1.  Opened hangouts xml file, and pasted the following lines (L1-8) from the backup file produced by the SMS B&R app on a new line at the top of the file.

    ```
    <?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
    <!--File Created By SMS Backup & Restore v10.07.105 on 25/06/2020 13:25:12-->
    <!--
    
    To view this file in a more readable format, visit https://synctech.com.au/view-backup/
    
    -->
    <smses count="23" backup_set="78f78bdc-aba9-47a3-882e-7f3664ffc225" backup_date="1593113112567" type="full">
    ```
1. On line 8, replaced the `count` value with the one from my original file on the line below.
1. Deleted the `<smses ...>` opening tag produced by this tool on the line below, and saved the file
1. Opened SMS B&R, selected Restore, and followed the instructions (see above) to navigate to the file with the System Browser.  The file was now selectable, and I was able to restore it into Messages.
